[package]
name = "STRdust"
version = "0.2.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.6", features = ["derive"] }
env_logger = "0.10.0"
flate2 = "1.0.24"
log = "0.4.17"
rayon = "1.5.3"
rust-htslib = { version = "0.44.1", features = ["s3"] }
bio = "*"
human-sort = "0.2.2"
# minimap2 = "0.1.14"
minimap2 = { git = "https://github.com/jguhlin/minimap2-rs.git", features = [
    "htslib",
] }
kodama = "0.3.0"
regex = "1.8.1"
rust-spoa = "0.2.4"
url = "2.3.1"
distance = "0.4.0"
levenshtein = "1.0.5"
rand = "0.8.5"

[dev-dependencies]
ctor = "*"
