[package]
name = "STRdust"
version = "0.8.1"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.6", features = ["derive"] }
env_logger = "0.10.0"
flate2 = "1.0.24"
log = "0.4.17"
rayon = "1.5.3"
rust-htslib = { version = "0.46.0", features = ["s3", "curl"] }
bio = { git = "https://github.com/lorewar2/rust-bio.git", branch = "reverse_edge_fix" }
human-sort = "0.2.2"
minimap2 = { version = "0.1.16", features = ["htslib"] }
kodama = "0.3.0"
regex = "1.8.1"
url = "2.3.1"
distance = "0.4.0"
levenshtein = "1.0.5"
rand = "0.8.5"
libz-sys = "1.1.12"
libc = "0.2.147"
petgraph = "0.6.4"
hts-sys = "2.1.1"
reqwest = { version = "0.11", features = ["blocking", "json"] }
indicatif = { version = "0.17.1", features = ["rayon"] }

[dev-dependencies]
ctor = "*"
