[package]
name = "STRdust"
version = "0.11.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.6", features = ["derive"] }
env_logger = "0.11.6"
flate2 = "1.0.35"
log = "0.4.25"
rayon = "1.5.3"
rust-htslib = { version = "0.49.0", features = ["s3", "curl"] }
bio = { git = "https://github.com/lorewar2/rust-bio.git", branch = "reverse_edge_fix" }
human-sort = "0.2.2"
minimap2 = { version = "0.1.20", features = ["htslib"] }
kodama = "0.3.0"
regex = "1.11.1"
url = "2.5.4"
distance = "0.4.0"
levenshtein = "1.0.5"
rand = "0.8.5"
libz-sys = "1.1.21"
libc = "0.2.147"
petgraph = "0.7.1"
hts-sys = "2.1.1"
reqwest = { version = "0.12.5", features = ["blocking", "json"] }
indicatif = { version = "0.17.9", features = ["rayon"] }
chrono = "0.4.39"

[dev-dependencies]
ctor = "*"
