[package]
name = "STRdust"
version = "0.1.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.6", features = ["derive"] }
env_logger = "0.9.0"
flate2 = "1.0.24"
log = "0.4.17"
rayon = "1.5.3"
rust-htslib = "0.38.2"
bio = "*"
human-sort = "0.2.2"
# minimap2 = "0.1.11"
minimap2 = { git = "https://github.com/jguhlin/minimap2-rs.git" }
regex = "1.8.1"
rust-spoa = "0.2.4"

[dev-dependencies]
ctor = "*"
